apiVersion: v2
name: cdsctf
description: The CdsCTF project is an innovative and high-performance CTF platform.
type: application
version: 1.0.1
appVersion: 1.8.2
kubeVersion: ">=1.22.0-0"
keywords:
  - ctf
home: https://cdsctf.e23.dev
sources:
  - https://github.com/ElaBosak233/cdsctf
  - https://github.com/cdsctf/helm-charts
maintainers:
  - name: Ela
    email: i@e23.dev
