apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-pvc
  namespace: {{ include "cdsctf.namespace" . }}
  labels:
    app: server
    {{- include "cdsctf.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.server.persistence.size }}
  storageClassName: {{ .Values.server.persistence.storageClass }}
---

{{- if .Values.db.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: {{ include "cdsctf.namespace" . }}
  labels:
    app: db
    {{- include "cdsctf.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.persistence.size }}
  storageClassName: {{ .Values.db.persistence.storageClass }}
---
{{- end }}

{{- if .Values.queue.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: queue-pvc
  namespace: {{ include "cdsctf.namespace" . }}
  labels:
    app: queue
    {{- include "cdsctf.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.queue.persistence.size }}
  storageClassName: {{ .Values.queue.persistence.storageClass }}
---
{{- end }}

{{- if .Values.cache.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache-pvc
  namespace: {{ include "cdsctf.namespace" . }}
  labels:
    app: cache
    {{- include "cdsctf.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cache.persistence.size }}
  storageClassName: {{ .Values.cache.persistence.storageClass }}
---
{{- end }}