{{- if .Values.server.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: server-sa
  namespace: {{ include "cdsctf.namespace" . }}
  labels:
    {{- include "cdsctf.labels" . | nindent 4 }}
---
{{- end -}}